name:        th-nowq
version:     0.1.0.0
synopsis:    Template Haskell splice that expands to current time

description: TH splice that expands to current time as a string
             literal in ISO-8601 format. Can be used to embed the
             compilation timestamp in your application.

github:      dzhus/th-nowq
license:     BSD3
author:      Dmitry Dzhus
maintainer:  dima@dzhus.org
category:    Template Haskell

extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat

dependencies:
  - base < 5

library:
  source-dirs: src
  dependencies:
    - template-haskell
    - time

tests:
  readme:
    main: README.lhs
    ghc-options:  -pgmL markdown-unlit
    dependencies:
      - th-nowq
